#ifndef LOGIC_EXPRESSIONS_H
#define LOGIC_EXPRESSIONS_H

typedef enum Operator
{
    GREATER_THAN,
    GREATER_EQUAL,
    SMALLER_THAN,
    SMALLER_EQUAL,
    EQUALS

} Operator;

#endif // LOGIC_EXPRESSIONS_H